workflows:
  android_webview_debug:
    name: GraFit Android WebView Debug
    environment:
      java: 21
    scripts:
      - name: Build debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew --no-daemon app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk

  android_webview_release:
    name: GraFit Android WebView Release
    environment:
      java: 21
    scripts:
      - name: Build release APK
        script: |
          chmod +x ./gradlew
          ./gradlew --no-daemon app:assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk